"""
Populate Database with Comprehensive Sample Data
Basert på GRT (Gordon's Reloading Tool) struktur og data
"""

from src.database.database import get_database


def populate_sample_data():
    """Populate database with realistic sample data based on GRT"""
    db = get_database()

    print("🔧 Populating database with GRT-style sample data...")
    print("   (Based on Gordon's Reloading Tool structure)\n")

    # 1. BULLETS - Comprehensive list from GRT
    print("📦 Adding bullets...")
    bullets = [
        # 6.5mm (.264") - Popular match bullets
        (
            "Lapua Scenar 139gr",
            "Lapua",
            "6.5mm",
            139,
            0.290,
            0.615,
            "Match/Target",
            "G7 BC: 0.290, extremely consistent",
        ),
        (
            "Lapua Scenar-L 136gr",
            "Lapua",
            "6.5mm",
            136,
            0.285,
            0.607,
            "Match",
            "Boat tail, excellent accuracy",
        ),
        (
            "Berger 140gr Hybrid Target",
            "Berger",
            "6.5mm",
            140,
            0.287,
            0.618,
            "Match",
            "Hybrid ogive, forgiving seating depth",
        ),
        (
            "Berger 156gr EOL Elite Hunter",
            "Berger",
            "6.5mm",
            156,
            0.347,
            0.679,
            "Match/Hunting",
            "Extreme BC for long range",
        ),
        (
            "Sierra MatchKing 142gr HPBT",
            "Sierra",
            "6.5mm",
            142,
            0.295,
            0.626,
            "Match",
            "Gold standard for 6.5 Creedmoor",
        ),
        (
            "Hornady ELD-M 147gr",
            "Hornady",
            "6.5mm",
            147,
            0.351,
            0.697,
            "Match",
            "Heat shield tip, high BC",
        ),
        (
            "Hornady ELD-X 143gr",
            "Hornady",
            "6.5mm",
            143,
            0.315,
            0.625,
            "Hunting",
            "Controlled expansion",
        ),
        (
            "Nosler RDF 140gr",
            "Nosler",
            "6.5mm",
            140,
            0.283,
            0.602,
            "Match",
            "Reduced Drag Factor",
        ),
        # .308" (7.62mm) - Classic .308 Win bullets
        (
            "Sierra MatchKing 168gr HPBT",
            "Sierra",
            "7.62mm",
            168,
            0.231,
            0.462,
            "Match",
            ".308 Win classic, proven accuracy",
        ),
        (
            "Sierra MatchKing 175gr HPBT",
            "Sierra",
            "7.62mm",
            175,
            0.243,
            0.505,
            "Match",
            "Excellent for 600-1000m",
        ),
        (
            "Berger 175gr OTM Tactical",
            "Berger",
            "7.62mm",
            175,
            0.243,
            0.505,
            "Match/Tactical",
            "Military sniper choice",
        ),
        (
            "Berger 185gr Juggernaut OTM",
            "Berger",
            "7.62mm",
            185,
            0.278,
            0.556,
            "Match",
            "High BC for .308",
        ),
        (
            "Lapua Scenar 185gr",
            "Lapua",
            "7.62mm",
            185,
            0.259,
            0.525,
            "Match",
            "Very consistent, clean",
        ),
        (
            "Lapua Scenar-L 175gr",
            "Lapua",
            "7.62mm",
            175,
            0.243,
            0.490,
            "Match",
            "Boat tail, match grade",
        ),
        (
            "Hornady ELD-M 178gr",
            "Hornady",
            "7.62mm",
            178,
            0.270,
            0.535,
            "Match",
            "Good BC, affordable",
        ),
        (
            "Hornady A-MAX 168gr",
            "Hornady",
            "7.62mm",
            168,
            0.230,
            0.475,
            "Match",
            "Classic match bullet",
        ),
        # .224" (5.56mm) - AR-15 / .223 Rem bullets
        (
            "Sierra MatchKing 77gr HPBT",
            "Sierra",
            "5.56mm",
            77,
            0.196,
            0.372,
            "Match",
            "Service Rifle standard",
        ),
        (
            "Sierra MatchKing 69gr HPBT",
            "Sierra",
            "5.56mm",
            69,
            0.186,
            0.355,
            "Match",
            "Excellent in 1:8 twist",
        ),
        (
            "Berger 73gr BT Target",
            "Berger",
            "5.56mm",
            73,
            0.193,
            0.370,
            "Match",
            "Very accurate, low ES",
        ),
        (
            "Berger 80gr VLD Target",
            "Berger",
            "5.56mm",
            80,
            0.210,
            0.455,
            "Match",
            "Requires fast twist (1:7)",
        ),
        (
            "Hornady ELD-M 80.5gr",
            "Hornady",
            "5.56mm",
            80.5,
            0.210,
            0.395,
            "Match",
            "High BC for .223",
        ),
        (
            "Hornady BTHP 75gr",
            "Hornady",
            "5.56mm",
            75,
            0.200,
            0.395,
            "Match",
            "Match grade, affordable",
        ),
        (
            "Nosler RDF 70gr",
            "Nosler",
            "5.56mm",
            70,
            0.219,
            0.416,
            "Match",
            "Reduced drag, consistent",
        ),
        (
            "Lapua Scenar 69gr",
            "Lapua",
            "5.56mm",
            69,
            0.184,
            0.355,
            "Match",
            "Premium quality",
        ),
        # 6mm (.243") - 6mm Creedmoor / .243 Win
        (
            "Berger 105gr Hybrid Target",
            "Berger",
            "6mm",
            105,
            0.270,
            0.547,
            "Match",
            "Hybrid ogive, forgiving",
        ),
        (
            "Berger 109gr LRHT",
            "Berger",
            "6mm",
            109,
            0.283,
            0.568,
            "Match",
            "Long Range Hybrid Target",
        ),
        (
            "Sierra MatchKing 107gr",
            "Sierra",
            "6mm",
            107,
            0.274,
            0.527,
            "Match",
            "Sierra precision",
        ),
        (
            "Hornady ELD-M 108gr",
            "Hornady",
            "6mm",
            108,
            0.274,
            0.536,
            "Match",
            "Heat shield tip",
        ),
        (
            "Lapua Scenar 105gr",
            "Lapua",
            "6mm",
            105,
            0.267,
            0.527,
            "Match",
            "Lapua consistency",
        ),
        # .338" - .338 Lapua Magnum
        (
            "Lapua Scenar 250gr",
            "Lapua",
            "8.6mm",
            250,
            0.322,
            0.662,
            "Match",
            ".338 LM standard",
        ),
        (
            "Lapua Scenar 285gr",
            "Lapua",
            "8.6mm",
            285,
            0.381,
            0.720,
            "Match",
            "Long range precision",
        ),
        (
            "Lapua Scenar-L 300gr",
            "Lapua",
            "8.6mm",
            300,
            0.413,
            0.790,
            "Match",
            "Scenar-L series, ultimate accuracy",
        ),
        (
            "Berger 300gr OTM Tactical",
            "Berger",
            "8.6mm",
            300,
            0.419,
            0.818,
            "Match/Tactical",
            "Extreme range",
        ),
        (
            "Sierra MatchKing 300gr",
            "Sierra",
            "8.6mm",
            300,
            0.411,
            0.768,
            "Match",
            "Proven ELR bullet",
        ),
        # Norma - Swedish Premium Bullets
        (
            "Norma Golden Target 6.5mm 140gr",
            "Norma",
            "6.5mm",
            140,
            0.585,
            0.295,
            "Match",
            "Swedish precision, hollow point boat tail",
        ),
        (
            "Norma Golden Target 7.62mm 168gr",
            "Norma",
            "7.62mm",
            168,
            0.462,
            0.231,
            "Match",
            "Premium match grade",
        ),
        (
            "Norma Diamond Line 6.5mm 130gr",
            "Norma",
            "6.5mm",
            130,
            0.545,
            0.275,
            "Hunting",
            "Bonded core, excellent expansion",
        ),
        (
            "Norma Oryx 7.62mm 180gr",
            "Norma",
            "7.62mm",
            180,
            0.430,
            0.215,
            "Hunting",
            "Bonded, reliable mushroom",
        ),
        (
            "Norma Tipstrike 6.5mm 143gr",
            "Norma",
            "6.5mm",
            143,
            0.615,
            0.310,
            "Hunting",
            "Polymer tip, high BC hunting",
        ),
        # Barnes - Copper Solid Bullets (Lead-Free)
        (
            "Barnes TSX 6.5mm 130gr",
            "Barnes",
            "6.5mm",
            130,
            0.440,
            0.220,
            "Hunting",
            "Triple-Shock X, 100% copper, deep penetration",
        ),
        (
            "Barnes TTSX 7.62mm 168gr",
            "Barnes",
            "7.62mm",
            168,
            0.470,
            0.235,
            "Hunting",
            "Tipped TSX, polymer tip, better BC",
        ),
        (
            "Barnes LRX 6.5mm 127gr",
            "Barnes",
            "6.5mm",
            127,
            0.468,
            0.234,
            "Hunting",
            "Long Range X, higher BC copper",
        ),
        (
            "Barnes Match Burner 7.62mm 175gr",
            "Barnes",
            "7.62mm",
            175,
            0.528,
            0.264,
            "Match",
            "Open tip match, affordable copper",
        ),
        # Nosler - Partition and AccuBond Series
        (
            "Nosler Partition 7.62mm 165gr",
            "Nosler",
            "7.62mm",
            165,
            0.410,
            0.205,
            "Hunting",
            "Dual-core design, legendary penetration",
        ),
        (
            "Nosler AccuBond 6.5mm 140gr",
            "Nosler",
            "6.5mm",
            140,
            0.509,
            0.255,
            "Hunting",
            "Bonded core, polymer tip",
        ),
        (
            "Nosler Ballistic Tip 6.5mm 129gr",
            "Nosler",
            "6.5mm",
            129,
            0.485,
            0.243,
            "Hunting",
            "Explosive expansion on deer",
        ),
        (
            "Nosler Custom Competition 7.62mm 168gr",
            "Nosler",
            "7.62mm",
            168,
            0.462,
            0.231,
            "Match",
            "Match grade at good price",
        ),
        # Lapua - Additional Popular Models
        (
            "Lapua MEGA 6.5mm 140gr",
            "Lapua",
            "6.5mm",
            140,
            0.462,
            0.231,
            "Hunting",
            "Soft point, reliable expansion, Scandinavian favorite",
        ),
        (
            "Lapua Naturalis 6.5mm 140gr",
            "Lapua",
            "6.5mm",
            140,
            0.490,
            0.245,
            "Hunting",
            "Lead-free copper, environmentally friendly",
        ),
        (
            "Lapua FMJ 7.62mm 123gr",
            "Lapua",
            "7.62mm",
            123,
            0.360,
            0.180,
            "Target/Plinking",
            "Full metal jacket, practice ammo",
        ),
        # Hornady - Extensive ELD and Hunting Line
        # ELD-M (Extremely Low Drag Match)
        (
            "Hornady ELD-M 6.5mm 140gr",
            "Hornady",
            "6.5mm",
            140,
            0.610,
            0.305,
            "Match",
            "Heat shield tip, G7 BC 0.305",
        ),
        (
            "Hornady ELD-M 6mm 103gr",
            "Hornady",
            "6mm",
            103,
            0.530,
            0.265,
            "Match",
            "6mm Creedmoor match",
        ),
        (
            "Hornady ELD-M 6mm 108gr",
            "Hornady",
            "6mm",
            108,
            0.536,
            0.274,
            "Match",
            "Long range 6mm",
        ),
        (
            "Hornady ELD-M .308 208gr",
            "Hornady",
            "7.62mm",
            208,
            0.670,
            0.336,
            "Match",
            "Subsonic and long range",
        ),
        (
            "Hornady ELD-M .308 225gr",
            "Hornady",
            "7.62mm",
            225,
            0.777,
            0.389,
            "Match",
            "Extreme BC for .308 Win",
        ),
        (
            "Hornady ELD-M .223 73gr",
            "Hornady",
            "5.56mm",
            73,
            0.398,
            0.199,
            "Match",
            "AR-15 match grade",
        ),
        (
            "Hornady ELD-M .223 88gr",
            "Hornady",
            "5.56mm",
            88,
            0.545,
            0.274,
            "Match",
            "Requires 1:7 twist",
        ),
        # ELD-X (Extremely Low Drag eXpanding - Hunting)
        (
            "Hornady ELD-X 6.5mm 120gr",
            "Hornady",
            "6.5mm",
            120,
            0.465,
            0.233,
            "Hunting",
            "Light 6.5mm hunting bullet",
        ),
        (
            "Hornady ELD-X 6.5mm 129gr",
            "Hornady",
            "6.5mm",
            129,
            0.525,
            0.263,
            "Hunting",
            "Optimized for 6.5 Creedmoor hunting",
        ),
        (
            "Hornady ELD-X 7mm 162gr",
            "Hornady",
            "7mm",
            162,
            0.631,
            0.316,
            "Hunting",
            "7mm Rem Mag favorite",
        ),
        (
            "Hornady ELD-X 7mm 175gr",
            "Hornady",
            "7mm",
            175,
            0.689,
            0.345,
            "Hunting",
            "Heavy 7mm long range hunting",
        ),
        (
            "Hornady ELD-X .308 178gr",
            "Hornady",
            "7.62mm",
            178,
            0.535,
            0.267,
            "Hunting",
            ".30-06 and .300 Win Mag",
        ),
        (
            "Hornady ELD-X .308 200gr",
            "Hornady",
            "7.62mm",
            200,
            0.626,
            0.313,
            "Hunting",
            "Heavy .30 cal hunting",
        ),
        # A-TIP (Advanced Tactical Interceptor Precision)
        (
            "Hornady A-TIP 6.5mm 153gr",
            "Hornady",
            "6.5mm",
            153,
            0.704,
            0.352,
            "Match",
            "Aluminum tip, extreme precision, ELR",
        ),
        (
            "Hornady A-TIP .308 230gr",
            "Hornady",
            "7.62mm",
            230,
            0.823,
            0.412,
            "Match",
            "Extreme long range .308",
        ),
        (
            "Hornady A-TIP .308 250gr",
            "Hornady",
            "7.62mm",
            250,
            0.878,
            0.439,
            "Match",
            "Heaviest .308, ELR king",
        ),
        # SST (Super Shock Tip - Classic Hunting)
        (
            "Hornady SST 6.5mm 129gr",
            "Hornady",
            "6.5mm",
            129,
            0.485,
            0.243,
            "Hunting",
            "Super Shock Tip, controlled expansion",
        ),
        (
            "Hornady SST .308 150gr",
            "Hornady",
            "7.62mm",
            150,
            0.415,
            0.207,
            "Hunting",
            "Classic .30-06 hunting",
        ),
        (
            "Hornady SST .308 165gr",
            "Hornady",
            "7.62mm",
            165,
            0.447,
            0.223,
            "Hunting",
            "Versatile .308 hunting weight",
        ),
        (
            "Hornady SST 7mm 154gr",
            "Hornady",
            "7mm",
            154,
            0.530,
            0.265,
            "Hunting",
            "7mm-08 favorite",
        ),
        # InterLock (Traditional Hunting)
        (
            "Hornady InterLock .308 150gr RN",
            "Hornady",
            "7.62mm",
            150,
            0.338,
            0.169,
            "Hunting",
            "Round nose for 30-30, lever actions",
        ),
        (
            "Hornady InterLock .308 150gr SP",
            "Hornady",
            "7.62mm",
            150,
            0.415,
            0.207,
            "Hunting",
            "Classic spire point, affordable",
        ),
        (
            "Hornady InterLock .308 165gr BTSP",
            "Hornady",
            "7.62mm",
            165,
            0.435,
            0.217,
            "Hunting",
            "Boat tail soft point",
        ),
        # V-MAX (Varmint)
        (
            "Hornady V-MAX .223 40gr",
            "Hornady",
            "5.56mm",
            40,
            0.200,
            0.100,
            "Varmint",
            "Ultra-fast varmint load",
        ),
        (
            "Hornady V-MAX .223 50gr",
            "Hornady",
            "5.56mm",
            50,
            0.242,
            0.121,
            "Varmint",
            "Standard .223 varmint",
        ),
        (
            "Hornady V-MAX .223 55gr",
            "Hornady",
            "5.56mm",
            55,
            0.255,
            0.128,
            "Varmint",
            "Explosive expansion on prairie dogs",
        ),
        (
            "Hornady V-MAX 6mm 58gr",
            "Hornady",
            "6mm",
            58,
            0.280,
            0.140,
            "Varmint",
            ".243 Win varmint screamer",
        ),
        # BTHP Match (Budget Match)
        (
            "Hornady BTHP .223 52gr",
            "Hornady",
            "5.56mm",
            52,
            0.255,
            0.127,
            "Match",
            "Affordable .223 match",
        ),
        (
            "Hornady BTHP .223 68gr",
            "Hornady",
            "5.56mm",
            68,
            0.327,
            0.164,
            "Match",
            "600 yard .223 match",
        ),
        (
            "Hornady BTHP .308 168gr",
            "Hornady",
            "7.62mm",
            168,
            0.450,
            0.225,
            "Match",
            "Budget .308 match grade",
        ),
        # FMJ-BT (Full Metal Jacket - Training/Plinking)
        (
            "Hornady FMJ-BT .223 55gr",
            "Hornady",
            "5.56mm",
            55,
            0.243,
            0.121,
            "Target/Plinking",
            "M193 ball equivalent, practice",
        ),
        (
            "Hornady FMJ-BT .308 150gr",
            "Hornady",
            "7.62mm",
            150,
            0.398,
            0.199,
            "Target/Plinking",
            "Affordable plinking/training",
        ),
        (
            "Hornady FMJ-BT .308 168gr",
            "Hornady",
            "7.62mm",
            168,
            0.435,
            0.217,
            "Target/Plinking",
            "Match-grade practice bullet",
        ),
        # Sierra - Additional GameKing Series
        (
            "Sierra GameKing 6.5mm 140gr SBT",
            "Sierra",
            "6.5mm",
            140,
            0.496,
            0.248,
            "Hunting",
            "Spitzer boat tail, proven on game",
        ),
        (
            "Sierra GameKing 7.62mm 165gr SBT",
            "Sierra",
            "7.62mm",
            165,
            0.447,
            0.223,
            "Hunting",
            "Versatile hunting bullet",
        ),
        (
            "Sierra BlitzKing 5.56mm 55gr",
            "Sierra",
            "5.56mm",
            55,
            0.271,
            0.136,
            "Varmint",
            "Explosive varmint performance",
        ),
        # Berger - Additional Hunting Series
        (
            "Berger VLD Hunting 6.5mm 140gr",
            "Berger",
            "6.5mm",
            140,
            0.612,
            0.306,
            "Hunting",
            "Very low drag, deep penetration then expansion",
        ),
        (
            "Berger Classic Hunter 7.62mm 168gr",
            "Berger",
            "7.62mm",
            168,
            0.473,
            0.236,
            "Hunting",
            "Hybrid design for hunting",
        ),
    ]

    for (
        name,
        manufacturer,
        caliber,
        weight,
        bc_g1,
        bc_g7,
        bullet_type,
        notes,
    ) in bullets:
        db.execute_query(
            """
            INSERT INTO bullets (name, manufacturer, caliber, weight_grains,
                               bc_g1, bc_g7, bullet_type, notes)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        """,
            (name, manufacturer, caliber, weight, bc_g1, bc_g7, bullet_type, notes),
        )

    print(f"  ✅ Added {len(bullets)} bullets")

    # 2. POWDER - Comprehensive GRT-style powder library
    print("\n💨 Adding powder...")
    powders = [
        # Hodgdon Extreme Series (temp stable)
        (
            "H4350",
            "Hodgdon",
            "Extruded",
            0.52,
            "6.5 Creedmoor #1 choice, very temp stable",
        ),
        (
            "Varget",
            "Hodgdon",
            "Extruded",
            0.53,
            "King of .308, also great for 6.5mm, temp stable",
        ),
        ("H4895", "Hodgdon", "Extruded", 0.54, ".223 Rem service rifle standard"),
        ("H1000", "Hodgdon", "Extruded", 0.48, "Slow magnum powder, .300 WM favorite"),
        ("Retumbo", "Hodgdon", "Extruded", 0.47, "Very slow, magnums and 6.5-284"),
        ("H4831SC", "Hodgdon", "Extruded", 0.51, "Short cut, magnums and 6.5x55"),
        ("H322", "Hodgdon", "Extruded", 0.56, "Fast .223 Rem varmint powder"),
        ("BL-C(2)", "Hodgdon", "Ball", 0.57, ".223 Rem ball powder, meters well"),
        ("CFE 223", "Hodgdon", "Ball", 0.56, "Copper fouling eraser technology"),
        # Alliant Reloader Series
        ("RL15", "Alliant", "Extruded", 0.52, ".308 Win, 6.5x55 match standard"),
        (
            "RL16",
            "Alliant",
            "Extruded",
            0.50,
            "Modern, very temp stable, 6.5 Creedmoor optimized",
        ),
        ("RL17", "Alliant", "Extruded", 0.51, "Fast magnum, high energy formula"),
        ("RL19", "Alliant", "Extruded", 0.50, "Medium-slow, .270 Win, .30-06"),
        ("RL22", "Alliant", "Extruded", 0.49, "Slow magnum, 7mm RM, .300 WM"),
        ("RL23", "Alliant", "Extruded", 0.51, "Temp stable, 6.5 Creedmoor/PRC, modern"),
        ("RL25", "Alliant", "Extruded", 0.48, "Very slow, .300 RUM, .338 Lapua"),
        (
            "RL26",
            "Alliant",
            "Extruded",
            0.48,
            "Ultra slow, max velocity in magnums, legendary",
        ),
        ("RL33", "Alliant", "Extruded", 0.46, "Extremely slow, .338 Lapua, .50 BMG"),
        (
            "Power Pro 2000-MR",
            "Alliant",
            "Ball",
            0.55,
            ".308 Win ball, meters excellent",
        ),
        ("Power Pro Varmint", "Alliant", "Ball", 0.56, ".223 Rem ball powder"),
        # IMR Classic Series
        (
            "IMR 3031",
            "IMR",
            "Extruded",
            0.55,
            ".308 Match, .223 Rem, 30-30 Winchester classic",
        ),
        ("IMR 4064", "IMR", "Extruded", 0.54, "Classic .308 Win powder, very accurate"),
        ("IMR 4895", "IMR", "Extruded", 0.55, "Military surplus favorite, .308, .223"),
        (
            "IMR 4350",
            "IMR",
            "Extruded",
            0.51,
            "Medium-slow, .270 Win, .30-06, versatile",
        ),
        ("IMR 4831", "IMR", "Extruded", 0.50, "Magnum powder, 7mm RM, .300 WM"),
        ("IMR 7828", "IMR", "Extruded", 0.49, "Very slow, .300 Win Mag heavy bullets"),
        (
            "IMR 7828 SSC",
            "IMR",
            "Extruded",
            0.49,
            "Super short cut 7828, meters better",
        ),
        ("IMR 8208 XBR", "IMR", "Extruded", 0.54, "Benchrest powder, .308 Win Match"),
        # IMR Enduron Series (temp stable with copper eraser)
        (
            "IMR 4166",
            "IMR",
            "Extruded",
            0.53,
            "Enduron, .308 Win, copper fouling reducer",
        ),
        ("IMR 4451", "IMR", "Extruded", 0.52, "Enduron, 6.5 Creedmoor, temp stable"),
        ("IMR 4955", "IMR", "Extruded", 0.50, "Enduron, 6.5 PRC, 7mm RM"),
        ("IMR 7977", "IMR", "Extruded", 0.48, "Enduron, .300 Win Mag, slow burner"),
        # Vihtavuori N100-Series (single-base, very clean)
        (
            "N110",
            "Vihtavuori",
            "Extruded",
            0.800,
            "Fastest N100, .22 Hornet, .30 Carbine",
        ),
        ("N120", "Vihtavuori", "Extruded", 0.860, ".300 Blackout, 7.62x39"),
        (
            "N130",
            "Vihtavuori",
            "Extruded",
            0.870,
            "Fast, .223 Rem light bullets, 6mm PPC",
        ),
        (
            "N133",
            "Vihtavuori",
            "Extruded",
            0.870,
            "Legendary benchrest powder, 6mm PPC",
        ),
        ("N135", "Vihtavuori", "Extruded", 0.870, ".308 Win <155gr, 6mm BR Norma"),
        (
            "N140",
            "Vihtavuori",
            "Extruded",
            0.910,
            "Versatile, .223 to .375 H&H, very clean",
        ),
        (
            "N150",
            "Vihtavuori",
            "Extruded",
            0.910,
            "Slow, .308 Win 175-200gr, 6.5x55 140-160gr",
        ),
        (
            "N160",
            "Vihtavuori",
            "Extruded",
            0.920,
            "6.5-284, .270 Win, magnums, temp stable",
        ),
        (
            "N165",
            "Vihtavuori",
            "Extruded",
            0.920,
            "Very slow, heavy bullets, .338 Lapua",
        ),
        (
            "N170",
            "Vihtavuori",
            "Extruded",
            0.960,
            "Slowest N100, .300 Wby Mag, .300 RUM",
        ),
        # Vihtavuori N500-Series (double-base with nitroglycerin, high energy)
        ("N530", "Vihtavuori", "Extruded", 0.930, "Fast N500, .223/5.56, .308 <155gr"),
        (
            "N540",
            "Vihtavuori",
            "Extruded",
            0.940,
            ".223 heavy, 6.5 Creedmoor, .308 Win",
        ),
        ("N550", "Vihtavuori", "Extruded", 0.940, "Slow, 6.5x55 heavy, .30-06 heavy"),
        (
            "N555",
            "Vihtavuori",
            "Extruded",
            0.900,
            "Developed for 6.5 Creedmoor competition",
        ),
        (
            "N560",
            "Vihtavuori",
            "Extruded",
            0.960,
            "Very slow, .270 Win, 7mm Mag, .300 WM",
        ),
        ("N565", "Vihtavuori", "Extruded", 0.960, ".338 Lapua 250gr, 7mm RM, .300 WM"),
        ("N568", "Vihtavuori", "Extruded", 0.907, "6.5 PRC, .300 PRC, .338 Lapua"),
        (
            "N570",
            "Vihtavuori",
            "Extruded",
            0.960,
            "Slowest N500, 6.5-284, .300 RUM, .338 LM",
        ),
        # Norma Series (Swedish precision)
        ("Norma 200", "Norma", "Ball", 0.59, "Fast ball, .222 Rem, .223 Rem"),
        ("Norma 201", "Norma", "Extruded", 0.57, "Fast extruded, .223 Rem, 6mm PPC"),
        ("Norma 202", "Norma", "Extruded", 0.56, "Medium-fast, .308 Win <155gr"),
        ("Norma 203B", "Norma", "Ball", 0.58, "Ball powder, .223 Rem, meters well"),
        ("Norma 204", "Norma", "Extruded", 0.55, ".308 Win standard, 6.5x55"),
        ("Norma 205", "Norma", "Extruded", 0.54, ".30-06, .308 Win heavy bullets"),
        ("Norma URP", "Norma", "Extruded", 0.53, "Universal Rifle Powder, .308 Win"),
        (
            "Norma MRP",
            "Norma",
            "Extruded",
            0.48,
            "Magnum Rifle Powder, 7mm RM, .300 WM",
        ),
        (
            "Norma MRP 2",
            "Norma",
            "Extruded",
            0.47,
            "Slower MRP, .338 Lapua, ultra magnums",
        ),
        # Accurate Arms (Western Powders)
        ("AA 2230", "Accurate", "Ball", 0.58, ".223 Rem fast ball"),
        ("AA 2520", "Accurate", "Ball", 0.57, ".223 Rem standard ball powder"),
        ("AA 2495", "Accurate", "Extruded", 0.54, ".308 Win match grade"),
        (
            "AA 2495BR",
            "Accurate",
            "Extruded",
            0.54,
            "Benchrest .308 Win, extra consistent",
        ),
        ("AA 2700", "Accurate", "Ball", 0.55, "6.5 Creedmoor ball powder"),
        ("AA 4064", "Accurate", "Extruded", 0.54, ".308 Win, similar to IMR 4064"),
        ("AA 4350", "Accurate", "Extruded", 0.52, "6.5 Creedmoor, .270 Win"),
        # Lovex / Reload Swiss
        ("RS 50", "ReloadSwiss", "Extruded", 0.54, ".308 Win precise"),
        ("RS 52", "ReloadSwiss", "Extruded", 0.53, "6.5 Creedmoor alternative"),
        ("RS 60", "ReloadSwiss", "Extruded", 0.52, "Medium-slow"),
        ("RS 62", "ReloadSwiss", "Extruded", 0.51, "6.5x55, magnums"),
    ]

    for name, manufacturer, powder_type, density, notes in powders:
        db.execute_query(
            """
            INSERT INTO powder (name, manufacturer, type, density, notes)
            VALUES (?, ?, ?, ?, ?)
        """,
            (name, manufacturer, powder_type, density, notes),
        )

    print(f"  ✅ Added {len(powders)} powders")

    # 3. PRIMERS - Comprehensive primer library
    print("\n💥 Adding primers...")
    primers = [
        # CCI Large Rifle
        (
            "CCI 200 Large Rifle",
            "Large Rifle",
            "CCI",
            "Standard large rifle primer, reliable",
        ),
        (
            "CCI BR-2 Large Rifle Benchrest",
            "Large Rifle Benchrest",
            "CCI",
            "Benchrest primer, very consistent ignition",
        ),
        (
            "CCI 250 Large Rifle Magnum",
            "Large Rifle Magnum",
            "CCI",
            "Magnum primer for slow/compressed loads",
        ),
        ("CCI 34 Large Rifle Military", "Large Rifle", "CCI", "Mil-spec, harder cup"),
        # CCI Small Rifle
        ("CCI 400 Small Rifle", "Small Rifle", "CCI", "Standard small rifle primer"),
        (
            "CCI BR-4 Small Rifle Benchrest",
            "Small Rifle Benchrest",
            "CCI",
            "Benchrest small rifle, match grade",
        ),
        (
            "CCI 450 Small Rifle Magnum",
            "Small Rifle Magnum",
            "CCI",
            "Magnum for compressed .223 loads",
        ),
        (
            "CCI 41 Small Rifle Military",
            "Small Rifle",
            "CCI",
            "Mil-spec, hard cup, AR-15 standard",
        ),
        # Federal Large Rifle
        ("Federal 210 Large Rifle", "Large Rifle", "Federal", "Standard large rifle"),
        (
            "Federal 210M Large Rifle Match",
            "Large Rifle Match",
            "Federal",
            "Gold standard match primer",
        ),
        (
            "Federal 215 Large Rifle Magnum",
            "Large Rifle Magnum",
            "Federal",
            "Magnum primer",
        ),
        (
            "Federal GM210M Gold Medal Match",
            "Large Rifle Match",
            "Federal",
            "Premium match primer",
        ),
        # Federal Small Rifle
        ("Federal 205 Small Rifle", "Small Rifle", "Federal", "Standard small rifle"),
        (
            "Federal 205M Small Rifle Match",
            "Small Rifle Match",
            "Federal",
            "Match primer for .223 Rem",
        ),
        ("Federal 205AR Small Rifle", "Small Rifle", "Federal", "AR-15 optimized"),
        # Remington (older stock)
        (
            "Remington 9 1/2 Large Rifle",
            "Large Rifle",
            "Remington",
            "Standard large rifle",
        ),
        (
            "Remington 9 1/2M Large Rifle Match",
            "Large Rifle Match",
            "Remington",
            "Match grade",
        ),
        (
            "Remington 7 1/2 Small Rifle",
            "Small Rifle",
            "Remington",
            "Standard small rifle",
        ),
        (
            "Remington 7 1/2 BR Small Rifle Benchrest",
            "Small Rifle Benchrest",
            "Remington",
            "Benchrest primer",
        ),
        # Winchester
        (
            "Winchester WLR Large Rifle",
            "Large Rifle",
            "Winchester",
            "Standard large rifle",
        ),
        (
            "Winchester WLRM Large Rifle Magnum",
            "Large Rifle Magnum",
            "Winchester",
            "Magnum primer",
        ),
        (
            "Winchester WSR Small Rifle",
            "Small Rifle",
            "Winchester",
            "Standard small rifle",
        ),
        (
            "Winchester WSRM Small Rifle Magnum",
            "Small Rifle Magnum",
            "Winchester",
            "Magnum small rifle",
        ),
        # European - Murom (Russian)
        (
            "Murom KVB-223 Small Rifle",
            "Small Rifle Match",
            "Murom",
            "Russian match primer, excellent consistency",
        ),
        (
            "Murom KVB-308 Large Rifle",
            "Large Rifle Match",
            "Murom",
            "Russian match primer for .308",
        ),
        # European - RWS
        ("RWS 5341 Large Rifle", "Large Rifle", "RWS", "German precision primer"),
        ("RWS 5333 Small Rifle", "Small Rifle", "RWS", "German small rifle"),
        # European - Fiocchi
        ("Fiocchi Large Rifle", "Large Rifle", "Fiocchi", "Italian primer"),
        ("Fiocchi Small Rifle", "Small Rifle", "Fiocchi", "Italian small rifle"),
    ]

    for name, primer_type, manufacturer, notes in primers:
        db.execute_query(
            """
            INSERT INTO primers (name, type, manufacturer, notes)
            VALUES (?, ?, ?, ?)
        """,
            (name, primer_type, manufacturer, notes),
        )

    print(f"  ✅ Added {len(primers)} primers")

    # 4. CASES
    print("\n🥉 Adding brass/cases...")
    cases = [
        (
            "Lapua 6.5 Creedmoor",
            "Lapua",
            "6.5 Creedmoor",
            100,
            "LOT-2024-001",
            52.5,
            163.0,
        ),
        (
            "Peterson 6.5 Creedmoor SRP",
            "Peterson",
            "6.5 Creedmoor",
            100,
            "LOT-2024-002",
            52.8,
            165.5,
        ),
        (
            "Alpha Munitions 6.5 CM",
            "Alpha",
            "6.5 Creedmoor",
            100,
            "LOT-2024-003",
            52.3,
            162.0,
        ),
        (
            "Lapua .308 Win Palma",
            "Lapua",
            ".308 Winchester",
            100,
            "LOT-2024-004",
            54.5,
            172.0,
        ),
        (
            "Peterson .308 Win",
            "Peterson",
            ".308 Winchester",
            100,
            "LOT-2024-005",
            54.0,
            170.5,
        ),
        ("Lapua .223 Rem", "Lapua", ".223 Remington", 100, "LOT-2024-006", 30.5, 94.0),
    ]

    for name, manufacturer, caliber, quantity, lot_number, capacity, weight in cases:
        db.execute_query(
            """
            INSERT INTO cases (name, manufacturer, caliber, quantity, lot_number,
                             case_capacity_gr_h2o, avg_weight_gr, times_fired, material)
            VALUES (?, ?, ?, ?, ?, ?, ?, 0, 'brass')
        """,
            (name, manufacturer, caliber, quantity, lot_number, capacity, weight),
        )

    print(f"  ✅ Added {len(cases)} case lots")

    # 5. RIFLES
    print("\n🔫 Adding rifles...")
    rifles = [
        (
            "Tikka T3x TAC A1 6.5 CM",
            "6.5 Creedmoor",
            24.0,
            "1:8",
            "Bolt Action",
            "Tikka",
        ),
        (
            "Bergara B-14 HMR .308",
            ".308 Winchester",
            20.0,
            "1:10",
            "Bolt Action",
            "Bergara",
        ),
        ("AR-15 SPR Mk12 Mod 0", ".223 Remington", 18.0, "1:7", "Semi-Auto", "Custom"),
    ]

    for name, caliber, barrel_length, twist, action, manufacturer in rifles:
        db.execute_query(
            """
            INSERT INTO rifles (name, caliber, barrel_length, twist_rate, action_type, manufacturer)
            VALUES (?, ?, ?, ?, ?, ?)
        """,
            (name, caliber, barrel_length, twist, action, manufacturer),
        )

    print(f"  ✅ Added {len(rifles)} rifles")

    db.commit()
    print("\n✅ Database populated successfully!")
    print("\nYou can now use Smart Loading Wizard with actual data! 🎉")


if __name__ == "__main__":
    populate_sample_data()
