"""Simple label/sheet export helpers.

Creates a human-readable label text for an `ammo_profile` or `qc_batch` including
component names and any available lot/patch information. Keeps implementation
dependency-free (plain text or CSV output) so the host can print or generate
PDFs externally.
"""

from typing import Any, Optional


def _safe_row(row, key, default=""):
    try:
        return row[key] if row and key in row.keys() else default
    except Exception:
        return default


def generate_label_text(
    db: Any, ammo_profile_id: Optional[int] = None, batch_id: Optional[int] = None
) -> str:
    """Return a text label for the given ammo_profile_id or qc batch id.

    Preference: if ammo_profile_id provided, use that. Otherwise use batch_id
    to look up associated ammo_profile or compose a generic batch label.
    """
    cur = db.cursor
    lines = []
    lines.append("Reloading Workshop - Load Label")
    lines.append("---------------------------------")

    if ammo_profile_id:
        cur.execute("SELECT * FROM ammo_profiles WHERE id = ?", (ammo_profile_id,))
        ap = cur.fetchone()
        if ap:
            lines.append(f"Profile ID: {ap['id']}")
            lines.append(f"Name: {ap.get('name','')}")
            lines.append(f"Rifle ID: {ap.get('rifle_id','')}")
            lines.append(f"Caliber: {ap.get('caliber','')}")
            lines.append(f"Charge (gr): {ap.get('powder_charge','')}")
            lines.append(f"COAL (mm): {ap.get('coal','')}")
            lines.append(f"CBTO (mm): {ap.get('cbto','')}")

            # Components: try to list names and any lot fields if present
            try:
                if ap.get("bullet_id"):
                    cur.execute(
                        "SELECT name FROM bullet_data WHERE id = ?", (ap["bullet_id"],)
                    )
                    b = cur.fetchone()
                    lines.append(f"Bullet: {b[0] if b else ap.get('bullet_id')}")
                if ap.get("powder_id"):
                    cur.execute(
                        "SELECT name FROM powder_data WHERE id = ?", (ap["powder_id"],)
                    )
                    p = cur.fetchone()
                    lines.append(f"Powder: {p[0] if p else ap.get('powder_id')}")
                if ap.get("case_id"):
                    cur.execute("SELECT name FROM cases WHERE id = ?", (ap["case_id"],))
                    c = cur.fetchone()
                    lines.append(f"Case: {c[0] if c else ap.get('case_id')}")
                if ap.get("primer_id"):
                    cur.execute(
                        "SELECT name FROM primers WHERE id = ?", (ap["primer_id"],)
                    )
                    pr = cur.fetchone()
                    lines.append(f"Primer: {pr[0] if pr else ap.get('primer_id')}")
            except Exception:
                pass

            # Lot/patch information: best-effort lookup in ammo_profile fields
            lot = ap.get("component_lot") if "component_lot" in ap.keys() else None
            patch = ap.get("patch") if "patch" in ap.keys() else None
            if lot:
                lines.append(f"Lot: {lot}")
            if patch:
                lines.append(f"Patch: {patch}")

            lines.append("")
            lines.append("Label generated by Reloading Workshop")
            return "\n".join(lines)

    # If batch_id provided, try to produce a batch-centric label
    if batch_id:
        cur.execute("SELECT * FROM qc_batches WHERE id = ?", (batch_id,))
        b = cur.fetchone()
        if b:
            lines.append(f"Batch ID: {b['id']}")
            lines.append(f"Name: {b.get('name','')}")
            lines.append(f"Batch size: {b.get('batch_size','')}")
            lines.append(f"Target charge: {b.get('target_charge','')}")
            lines.append("")
            lines.append("Measurements:")
            try:
                cur.execute(
                    "SELECT patron_number, value FROM qc_measurements WHERE batch_id = ? AND measurement_type = 'velocity' ORDER BY patron_number",
                    (batch_id,),
                )
                rows = cur.fetchall()
                for r in rows:
                    lines.append(f"#{r['patron_number']}: {r['value']}")
            except Exception:
                pass

            lines.append("")
            lines.append("Label generated by Reloading Workshop")
            return "\n".join(lines)

    return "No profile or batch specified."


def save_label_to_file(path: str, text: str) -> None:
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)
